name: millersvilleunderground
favicon: null
layout_spectrum: 0.8392586086411029
typography_spectrum: 0.6093245728407055
title: A Jesus Movement.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.22807963541708887
  lightness: 0.7500253794714808
  saturation: 0.09241690230555832
  rhythmicContrast: 0.7663844015914947
purpose: []
